# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Over The Wall
email: david.joseph.lowe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Professional QA for over 10 years. Love what I do, even if things get tossed over the wall.
 This is just a place to put musings and thoughts and maybe go a bit deeper on what I see others talking about.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Vexrm

# Build settings
markdown: kramdown
highlighter: rouge